WebAppKinesis/Models/Pacientes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppKinesis.Models
{
    public class Pacientes
    {
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Edad { get; set; }
        public string Profesion { get; set; }
        public string EstadoCivil { get; set; }
        public string NumHijos { get; set; }

        public HistoriaClinica HistPac { get; set; }

    }
}

WebAppKinesis/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppKinesis.Models;

namespace WebAppKinesis.Controllers
{
    public class PacienteController : Controller
    {
        string mensaje;

        public ActionResult CrearHistoriaPaciente()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearHistoriaPaciente(Pacientes pac)
        {
            ModelFacade facade = new ModelFacade();
            var result = facade.AddHistoria(pac);
            if (result == 1)
            {
                return View("AddExitoso", pac);
            }
            else
            {
                if (result == 2)
                {
                    mensaje = "El usuario ya se encuentra registrado en el sistema";
                    return RedirectToAction("ErrorUsuario");
                }
                else {
                    return View();
                }                
            }
        }
        public ActionResult AddExitoso()
        {
            return View();
        }

        public ActionResult ErrorUsuario()
        {
            ViewBag.error = mensaje;
            return View();
        }

 
        [HttpGet]
        public ActionResult ConsultarHistorias()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ConsultarHistorias(string NumCedula)
        {
            ModelFacade model = new ModelFacade();
            var per = model.BuscarPaciente(NumCedula);
            if (per != null)
            {
                return View("HistoriaPaciente", per);
            }
            else
            {
                ViewBag.message = "El usuario no se encuentra registrado en el sistema";
                return View("NoExisteCedula");
            }
            
        }
    }
}

WebAppKinesis/Views/Paciente/AddExitoso.cshtml
@model WebAppKinesis.Models.Pacientes
@{
    ViewBag.Title = "Exitoso - Kinesis";
}

<style>
    .btn a {
        color: white;
        text-decoration: none;
    }

    .regresar {
        width: 30%;
    }
</style>

<br />
<div class="text-center">
    <h1>La historia Clinical del Paciente </h1>
    <span class="alert-success">@Model.Nombres se ha registrado con exito con Fecha de registro: <b>@Model.HistPac.FechaRegistro</b> </span>
    <br />
    <h2>@ViewBag.message</h2>
    <div class="btn btn-success regresar">
        @Html.ActionLink("Regresar", "CrearHistoriaPaciente", "Paciente")
    </div>
    |

    <div class="btn btn-primary regresar">
        @Html.ActionLink("Consultar Detalles", "ConsultarHistorias", "Paciente")
    </div>
</div>

WebAppKinesis/Views/Paciente/ConsultarHistorias.cshtml
@{
    ViewBag.Title = "ConsultarHistorias";
}

<div class="container-full">
    <div class="row">

        <div class="col-md-12 text-center v-center">

            <h1 class="tittleCon">Consultar Historial Clinico Por Paciente</h1>
            <h5>Realiza la busqueda con el numero de cedula del paciente</h5>

            <br>
            @using (Html.BeginForm())
            {
                <div class="input-group input-group-lg offset-sm-2 col-sm-8">
                    <input type="text" class="form-control" name="NumCedula" placeholder="N° Cedula del Paciente" required autofocus="">
                    <span class="input-group-append"><button class="btn btn-lg btn-primary" type="submit">Buscar</button></span>
                </div>
                <br /><br /><br />
            }
        </div>

    </div>
</div>
<div>
    @Html.ActionLink("Regresar", "HomePage", "Home")
</div>

WebAppKinesis/Views/Paciente/CrearHistoriaPaciente.cshtml
@model WebAppKinesis.Models.Pacientes

@{
    ViewBag.Title = "Registrar Historia del Paciente";
}

<h2 style="margin-top: 50px;">Formulario de Registro Paciente y su Historia Medica</h2>

<div class="panel">
    <div class="panel-heading text-left"><h4>1. INFORMACION PERSONAL:</h4></div>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary()
        <div class="form-row">
            <div class="form-group col-md-8">
                <label class="float-left">Cedula </label>
                @Html.TextBoxFor(x => x.Cedula, new { @class = "form-control", @required = "" })
            </div>
            <div class="form-group col-md-4">
                <label class="float-left">Fecha de Registro</label>
                @Html.TextBoxFor(x => x.HistPac.FechaRegistro, new { @class = "form-control", @placeholder = DateTime.Today.Date.ToShortDateString(), @readonly = "" })
            </div>
        </div>

        <div class="form-group">
            <label class="float-left">Nombres y Apellidos</label>
            @Html.TextBoxFor(x => x.Nombres, new { @class = "form-control", @required = "" })
        </div>

        <div class="form-row">
            <div class="form-group col-md-7">
                <label class="float-left">Direccion</label>
                @Html.TextBoxFor(x => x.Direccion, new { @class = "form-control", @required = "" })
            </div>
            <div class="form-group col-md-5">
                <label class="float-left">Telefono</label>
                @Html.TextBoxFor(x => x.Telefono, new { @class = "form-control", @required = "" })
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="float-left">Fecha de nacimiento</label>
                @Html.TextBoxFor(x => x.FechaNacimiento, new { @class = "form-control", @required = "" })
            </div>

            <div class="form-group col-md-6">
                <label class="float-left">Edad</label>
                @Html.TextBoxFor(x => x.Edad, new { @class = "form-control", @required = "" })
            </div>
        </div>

        <div class="form-group">
            <label class="float-left">Profesion</label>
            @Html.TextBoxFor(x => x.Profesion, new { @class = "form-control", @required = "" })
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="float-left">Estado Civil</label>
                @Html.DropDownListFor(x => x.EstadoCivil, new[]
                                                                 {
                new SelectListItem() {Text = "Soltera", Value = "Soltera" },
                new SelectListItem() {Text = "Casada", Value = "Casada" },
            }, "Seleccione una opcion", new { @class = "form-control" })
            </div>
            <div class="form-group col-md-6">
                <label class="float-left">Numero de Hijos</label>
                @Html.TextBoxFor(x => x.NumHijos, new { @class = "form-control", @required = "" })
            </div>
        </div>

        <hr class="border" />
        <br />

        <div class="panel-heading text-left"><h4>2. DATOS SOBRE ESTADO DE SALUD Y MODO DE VIDA:</h4></div>
        <br />
        <div class="form-group">
            <label class="float-left">Sufre o a sufrido de problemas:</label>
            @Html.DropDownListFor(x => x.HistPac.DescEnfermedad, new[]
                      {
        new SelectListItem() {Text = "Cardiacos", Value = "Cardiacos"},
        new SelectListItem() {Text = "Endocrino", Value = "Endocrino"},
        new SelectListItem() {Text = "Digestivo", Value = "Digestivo" },
        new SelectListItem() {Text = "Circulacion", Value = "Circulacion" },
        new SelectListItem() {Text = "Tension Arterial", Value = "Tension Arterial" },
    }, "Seleccionar...", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label class="float-left">Otros:</label>
            @Html.TextBoxFor(x => x.HistPac.OtraEnfermedad, new { @class = "form-control" })
        </div>

        <div class="form-row">
            <div class="form-group col-md-3">
                <label class="float-left">Peso actual</label>
                @Html.TextBoxFor(x => x.HistPac.Peso, new { @class = "form-control", @placeholder = "Kilos", @required = "" })
            </div>

            <div class="form-group col-md-3">
                <label class="float-left">Talla </label>
                @Html.TextBoxFor(x => x.HistPac.Talla, new { @class = "form-control", @required = "" })
            </div>
            <div class="form-group col-md-3">
                <label class="float-left">Masa corporal</label>
                @Html.TextBoxFor(x => x.HistPac.MasaMuscular, new { @class = "form-control", @required = "" })
            </div>
            <div class="form-group col-md-3">
                <label class="float-left">Altura</label>
                @Html.TextBoxFor(x => x.HistPac.Altura, new { @class = "form-control", @required = "" })
            </div>
        </div>

        <div class="form-group">
            <label class="float-left">Silueta</label>
            @Html.DropDownListFor(x => x.HistPac.Silueta, new[]
                 {
        new SelectListItem() {Text = "Pequeña", Value = "Pequeña" },
        new SelectListItem() {Text = "Mediana", Value = "Mediana" },
        new SelectListItem() {Text = "Grande", Value = "Grande" },
        }, "Seleccionar...", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label class="float-left">Costumbres Alimenticias:</label>
            @Html.TextAreaFor(x => x.HistPac.CostumbreAlimenticias, new { @class = "form-control", @required = "" })
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="float-left" style="margin-right: 50px;"> Modo de Vida:</label>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(x => x.HistPac.ModoVida, "Activa", new { @class = "form-check-input" })
                    <label class="form-check-label">Activa</label>
                </div>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(x => x.HistPac.ModoVida, "Sedentaria", new { @class = "form-check-input" })
                    <label class="form-check-label">Sedentaria</label>
                </div>
            </div>
            <div class="form-group">
                <label style="margin-right: 30px;"> Fuma:</label>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(x => x.HistPac.SiFuma, "Si", new { @class = "form-check-input" })
                    <label class="form-check-label">Si</label>
                </div>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(x => x.HistPac.SiFuma, "No", new { @class = "form-check-input" })
                    <label class="form-check-label">No</label>
                </div>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(x => x.HistPac.SiFuma, "Ocasionalmente", new { @class = "form-check-input" })
                    <label class="form-check-label">Ocasionalmente</label>
                </div>
            </div>

        </div>

        <div class="form-group">
            <label class="float-left">Alcohol:</label>
            @Html.DropDownListFor(x => x.HistPac.SiAlcohol, new[]
                           {
    new SelectListItem() {Text = "Si", Value = "Si" },
    new SelectListItem() {Text = "No", Value = "No" },
    new SelectListItem() {Text = "Ocasionalmente", Value = "Ocasionalmente" },
}, "Seleccionar...", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label class="float-left">Calidad de Sueño</label>
            @Html.DropDownListFor(x => x.HistPac.CalidadSueño, new[]
                           {
    new SelectListItem() {Text = "Buena", Value = "Buena" },
    new SelectListItem() {Text = "Mala", Value = "Mala" },
    new SelectListItem() {Text = "Normal", Value = "Normal" },
}, "Seleccionar...", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label class="float-left">Deportes practicados</label>
            @Html.TextBoxFor(x => x.HistPac.DeportesPracticados, new { @class = "form-control", @required = "" })
        </div>
        <br />

        <button type="submit" id="btn-histo" class="btn btn-primary">Guardar</button>
    }
</div>

<br />
<div>
    @Html.ActionLink("Regresar", "HomePage", "Home")
</div>

WebAppKinesis/Views/Paciente/ErrorUsuario.cshtml
@{
    ViewBag.Title = "ErrorUsuario";
}

<h2>ErrorUsuario</h2>
<h4>@ViewBag.ErrorUser</h4>

WebAppKinesis/Views/Paciente/HistoriaPaciente.cshtml
@model WebAppKinesis.Models.Pacientes

@{
    ViewBag.Title = "Historia Paciente";
}

<h2 style="margin-top: 50px;">1. Informacion del Paciente</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profesion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumHijos)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.Profesion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.EstadoCivil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.NumHijos)
        </td>
    </tr>

</table>
<hr />
<br />

<h2>2. Informacion sobre estado de salud y modo de vida</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.DescEnfermedad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.OtraEnfermedad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.Talla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.Altura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.MasaMuscular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.Silueta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.DescEnfermedad)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.HistPac.CostumbreAlimenticias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HistPac.ModoVida)
        </th>

    </tr>

    <tr>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.DescEnfermedad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.OtraEnfermedad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.Peso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.Talla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.Altura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.MasaMuscular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.Silueta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.CostumbreAlimenticias)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.HistPac.ModoVida)
        </td>
    </tr>

</table>

    <p>
        @Html.ActionLink("Regresar", "ConsultarHistorias")
    </p>

WebAppKinesis/Views/Paciente/NoExisteCedula.cshtml
@{
    ViewBag.Title = "NoExisteCedula";
}

<style>
    .btn a {
        color: white;
        text-decoration: none;
    }

    .regresar {
        width: 30%;
    }
</style>

<div class="text-center">
    <h2 style="margin-top: 50px" ;>Error en  la consulta</h2>
    <br />
    <h3>@ViewBag.message</h3>
    <div class="btn btn-success regresar">
        @Html.ActionLink("Regresar", "ConsultarHistorias", "Paciente")
    </div>
</div>
<br />